compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

injectEnvironmentFiles:
  - .env.local

nodeLinker: node-modules

npmScopes:
  abrams-dev:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}
    npmPublishRegistry: https://registry.npmjs.org
    npmRegistryServer: https://registry.npmjs.org

yarnPath: .yarn/releases/yarn-sources.cjs
